In [4]:
import pandas as pd
import numpy as np

In [58]:
#take a look at the columns
df = pd.read_csv(".//open_refine/fertig/authors-tsv.tsv", sep="\t")
print(df.head())

                     Autor_in GND-Nummer            Bevorzugter Name  \
0  Harsdörffer, Georg Philipp  118546139  Harsdörffer, Georg Philipp
1      Meysenbug, Malwida von  118582054      Meysenbug, Malwida von
2               Lyncker, Karl  139259066               Lyncker, Karl
3        Hamann, Johann Georg  11854523X        Hamann, Johann Georg
4   Günther, Johann Christian  11854327X   Günther, Johann Christian

  Geburtsdatum Sterbedatum Geschlecht  Lebensdaten
0   1607-11-01  1658-09-17   Männlich  (1607–1658)
1   1816-10-28  1903-04-26   Weiblich  (1816–1903)
2   1823-02-24  1855-05-20   Männlich  (1823–1855)
3   1730-08-27  1788-06-21   Männlich  (1730–1788)
4   1695-04-08  1723-03-15   Männlich  (1695–1723)

In [62]:
import re

#enter the path of the tsv file
tsv_file_path = ".//open_refine/fertig/authors-tsv.tsv"

#get birth date function
def get_birth_year(birth_date):
    return int(birth_date.split("-")[0])

#get life span function
def get_start_year(life_span):
    match = re.match(r'\((\d{4})–(\d{4})\)', life_span)
    if match:
        return int(match.group(1))
    else:
        return None

#compare birth year with start year and print results
with open(tsv_file_path, "r", encoding="utf-8") as tsv_file:
    
    for index, line in enumerate(tsv_file):
        columns = line.strip().split("\t")
        if len(columns) < 7:  #check if there are 7 columns
            continue  #skip lines without enough columns
        
        birth_date = columns[3]  #birth_date is the 4th column
        life_span = columns[6]   #life_span is the 6th column
        
        try:
            birth_year = get_birth_year(birth_date)
            start_year = get_start_year(life_span)
            
            if birth_year != start_year:
                #pass
                print(f"Line {index}: birth year ({birth_year}) is not equal to start year life_span ({start_year})")
        except ValueError:
                pass
                #print(f"Error processing line: {line.split()}") #optional

Line 8: birth year (1544) is not equal to start year life_span (1545)
Line 28: birth year (1744) is not equal to start year life_span (1748)
Line 30: birth year (1861) is not equal to start year life_span (1860)
Line 55: birth year (1544) is not equal to start year life_span (1545)
Line 75: birth year (1744) is not equal to start year life_span (1748)
Line 77: birth year (1861) is not equal to start year life_span (1860)
Line 99: birth year (1564) is not equal to start year life_span (1546)
Line 109: birth year (1617) is not equal to start year life_span (1616)
Line 129: birth year (1505) is not equal to start year life_span (None)
Line 141: birth year (1550) is not equal to start year life_span (1560)
Line 143: birth year (1796) is not equal to start year life_span (1798)
Line 153: birth year (1690) is not equal to start year life_span (1699)
Line 158: birth year (1210) is not equal to start year life_span (1200)
Line 164: birth year (1830) is not equal to start year life_span (None)
Line 191: birth year (1792) is not equal to start year life_span (1855)
Line 203: birth year (1490) is not equal to start year life_span (None)
Line 218: birth year (1772) is not equal to start year life_span (None)
Line 225: birth year (1579) is not equal to start year life_span (1571)
Line 234: birth year (1864) is not equal to start year life_span (None)
Line 236: birth year (70) is not equal to start year life_span (None)
Line 246: birth year (1752) is not equal to start year life_span (1756)
Line 253: birth year (1815) is not equal to start year life_span (1852)
Line 257: birth year (1645) is not equal to start year life_span (1647)
Line 259: birth year (1828) is not equal to start year life_span (1836)
Line 267: birth year (1487) is not equal to start year life_span (None)
Line 271: birth year (1265) is not equal to start year life_span (1256)
Line 284: birth year (120) is not equal to start year life_span (None)
Line 306: birth year (1665) is not equal to start year life_span (None)
Line 340: birth year (1529) is not equal to start year life_span (None)
Line 353: birth year (1500) is not equal to start year life_span (1501)
Line 359: birth year (1823) is not equal to start year life_span (None)
Line 380: birth year (1816) is not equal to start year life_span (None)
Line 383: birth year (1483) is not equal to start year life_span (1494)
Line 390: birth year (1640) is not equal to start year life_span (None)
Line 393: birth year (1833) is not equal to start year life_span (1831)
Line 410: birth year (1480) is not equal to start year life_span (None)
Line 422: birth year (1535) is not equal to start year life_span (None)
Line 423: birth year (1744) is not equal to start year life_span (1748)
Line 425: birth year (1785) is not equal to start year life_span (1796)
Line 435: birth year (1470) is not equal to start year life_span (None)
Line 451: birth year (1711) is not equal to start year life_span (1714)
Line 459: birth year (123) is not equal to start year life_span (None)
Line 463: birth year (1343) is not equal to start year life_span (None)
Line 485: birth year (1484) is not equal to start year life_span (None)
Line 490: birth year (1465) is not equal to start year life_span (1470)
Line 492: birth year (1616) is not equal to start year life_span (None)
Line 494: birth year (1848) is not equal to start year life_span (1850)
Line 495: birth year (1622) is not equal to start year life_span (1621)
Line 506: birth year (1722) is not equal to start year life_span (None)
Line 510: birth year (1801) is not equal to start year life_span (None)
Line 517: birth year (1806) is not equal to start year life_span (1808)
Line 528: birth year (1797) is not equal to start year life_span (None)
Line 555: birth year (1870) is not equal to start year life_span (1819)
Line 561: birth year (1692) is not equal to start year life_span (None)
Line 568: birth year (1709) is not equal to start year life_span (1789)
Line 579: birth year (1505) is not equal to start year life_span (1500)
Line 589: birth year (1813) is not equal to start year life_span (None)
Line 590: birth year (1807) is not equal to start year life_span (1805)
Line 592: birth year (1460) is not equal to start year life_span (None)
Line 621: birth year (1505) is not equal to start year life_span (None)
Line 622: birth year (1634) is not equal to start year life_span (None)
Line 628: birth year (1570) is not equal to start year life_span (None)
Line 629: birth year (1543) is not equal to start year life_span (1544)
Line 636: birth year (1761) is not equal to start year life_span (None)
Line 668: birth year (1807) is not equal to start year life_span (1781)
Line 671: birth year (1731) is not equal to start year life_span (1735)
Line 685: birth year (1780) is not equal to start year life_span (1781)
Line 691: birth year (1767) is not equal to start year life_span (None)
Line 699: birth year (1500) is not equal to start year life_span (None)
Line 703: birth year (1835) is not equal to start year life_span (1781)
Line 709: birth year (1844) is not equal to start year life_span (1839)
Line 716: birth year (1315) is not equal to start year life_span (None)
Line 725: birth year (1487) is not equal to start year life_span (None)