In [2]:
import pandas as pd
import numpy as np
from collections import Counter
import random

source of the "products.csv": https://gist.github.com/petroniocandido/dbab9321b7d5770b7549682436bb2073

In [4]:
product_list = pd.read_csv("products.csv")
product_list = product_list["product_name"]
print(product_list)

random_products = random.choices(product_list, k=100)

0                             Chocolate Sandwich Cookies
1                                       All-Seasons Salt
2                   Robust Golden Unsweetened Oolong Tea
3      Smart Ones Classic Favorites Mini Rigatoni Wit...
4                              Green Chile Anytime Sauce
                             ...
994                    Sausage Smoked Sweet German Brand
995                   Honey Cinnamon Nut-Thins  Crackers
996                 Mini Double Chocolate Ice Cream Bars
997                              Hot Chopped Green Chili
998                     Original Organic Ville BBQ Sauce
Name: product_name, Length: 999, dtype: object

In [8]:
#random supply chain data
data = {
    "product": random_products,
    "stock": np.random.randint(5, 100, size=100),  # Stock levels between 5 and 100
    "delivery_time (days)": np.random.randint(1, 15, size=100),  # Delivery times between 1 and 15 days
    "sales_per_month": np.random.randint(1, 500, size=100)  # Sales between 1 and 500
}

df_supply = pd.DataFrame(data)

In [32]:
#20 low-stock products (< 20 units)
low_stock = df_supply[df_supply["Stock"] < 20]

#average, min delivery times & max delivery times
avg_delivery_time = df_supply["delivery_time (days)"].mean()
max_delivery_time = df_supply["delivery_time (days)"].max()
min_delivery_time = df_supply["delivery_time (days)"].min()

#best- and worst-selling products
top_sellers = df_supply.nlargest(10, "sales_per_month")
low_sellers = df_supply.nsmallest(10, "sales_per_month")

In [34]:
print(f"Average delivery time: {avg_delivery_time:.2f} days")
print(f"Longest delivery time: {max_delivery_time} days")
print(f"Shortest delivery time: {min_delivery_time} days")

Average delivery time: 7.28 days
Longest delivery time: 14 days
Shortest delivery time: 1 days

In [38]:
print("\nProducts with low stock:")
low_stock.sort_values("Stock", ascending=True)

Products with low stock:

,Product,Stock,Delivery_Time (Days),Sales_Per_Month
83,Embrace Sensitive Women's 5 Blade Disposable R...,10,1,267
94,Vitamin D3 Cholecalciferol Softgels,10,5,431
96,Seasonal Oikos Greek Yogurt,10,9,20
11,Supreme Pretzel Crackers,11,10,122
35,Wild Rice Blend,11,13,200
81,"Easy Grab 9\""x13\"" Oblong Glass Bakeware",11,14,251
66,Sloppy Joe,12,12,212
61,Washington State Merlot,14,5,171
78,Country Style Baked Beans,14,7,216
92,Double Control Small Roach Baits Insecticide,14,3,395
17,Tzatziki Cucumber Sauce,17,5,309
97,Thick Cut Italian 7-Herb Blend Crispbreads,17,6,187
12,Organic Whole Peeled Baby Carrots,18,3,142

In [44]:
print("\nTop 5 best-selling products:")
top_sellers

Top 5 best-selling products:

,Product,Stock,Delivery_Time (Days),Sales_Per_Month
76,Aspirin 325 Mg,33,13,499
19,Banana & Sweet Potato Organic Teething Wafers,87,14,491
59,Smoked Atlantic Nova Salmon,65,3,486
64,Mallow Oats Cereals,48,14,484
71,"Linguine, No. 6",84,14,483
85,Organic Shredded Mild Cheddar,56,5,472
74,"10\"" Bamboo Skewers",76,2,464
43,Brut Rosé,65,4,453
79,Sharp Cheddar,72,12,452
80,Aquaphor Healing Ointment,82,12,449

In [46]:
print("\nBottom 5 worst-selling products:")
low_sellers

Bottom 5 worst-selling products:

,Product,Stock,Delivery_Time (Days),Sales_Per_Month
84,Salted Caramel Ice Cream,78,4,9
98,Buffalo Style Chicken Strips,37,2,10
48,Artisan Spiced Pecan Turtle Ice Cream,37,10,18
96,Seasonal Oikos Greek Yogurt,10,9,20
4,Mirabelle Brut Rose,20,6,21
55,Clamato Chelada Beer,55,8,33
1,"Cold & Cough Formula, Effervescent Tablets, Ci...",27,1,38
70,Almond Honey Protein+ Bar,94,10,42
68,Chipotle & Roasted Garlic Seasoning,22,3,48
67,Mini Nilla Wafers Munch Pack,46,9,54