#### Aufgabe 3.1A

In [6]:
liste = [3, 5, 12, 17, 23] #beispiel

#mittelwert berechnen
mw = sum(liste)/len(liste)
print(mw)

#zähler unter wurzel für varianzberechnung
zaehler=0
for i in liste:
   zaehler += (i-mw)**2
print(zaehler)

#varianz berechnen
varianz = (zaehler/len(liste))**0.5
print(varianz)

#standard-abweichung
sa = varianz**0.5

print(sa)

12.0
276.0
7.429670248402684
2.725742146352564

#### Aufgabe 3.1B

In [2]:
import pandas as pd

pd.read_csv("0103_personen_drama_hamlet.csv", sep=";")

,id,label,gender,role,importance,per_mes_sps
0,1,Ghost,male,other,primary,0
1,2,Hamlet,male,protagonist,primary,358
2,3,Gertrude,female,other,secondary,69
3,4,Claudius,male,antagonist,primary,102
4,5,Ophelia,female,lover,primary,58
5,6,Laertes,male,antagonist,primary,62
6,7,Polonius,male,other,secondary,86
7,8,Reynaldo,male,other,minor,13
8,9,Horatio,male,other,secondary,109
9,10,Voltemand,male,other,minor,1
10,11,Cornelius,male,other,minor,1
11,12,Rosencrantz,male,other,minor,48
12,13,Guildenstern,male,other,minor,29
13,14,Osric,male,other,minor,25
14,15,Gentlemen,male,other,minor,1
15,16,A Lord,male,other,minor,3
16,17,Francisco,male,other,minor,8
17,18,Bernardo,male,other,minor,19
18,19,Marcellus,male,other,minor,37
19,20,Fortinbras,male,other,minor,6
20,21,Captain in Fortinbras Army,male,other,minor,7
21,22,Ambassodors to Denmark from England,male,other,minor,1
22,23,Players who take Proglogue,male,other,minor,1
23,24,Two Messengers,male,other,minor,1
24,25,Sailors,male,other,minor,2
25,26,Gravedigger = First Clown,male,other,minor,34
26,27,Gravedigger's companion = 2nd Clown,male,other,minor,12
27,28,Doctor of Divinity = Priest,male,other,minor,2
28,29,"Atenndants, Lords, Guards, Musicians, Laertes ...",male,other,minor,0